version: '2.1'

services:
  gitlab:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        buildno: 1
    image: doggie6/gitlab:9.3.4-ce.0
    restart: always
    command: ["assets/wrapper"]
    entrypoint: ["/root/entrypoint.sh"]
    container_name: gitlab
    hostname: gitlab.test.com
    volumes:
#      - /Users/sunday/gitlab/config:/etc/gitlab
#      - /Users/sunday/gitlab/data:/var/opt/gitlab
#      - /Users/sunday/gitlab/logs:/var/log/gitlab
       - volume-gitlab-data:/var/opt/gitlab
       - volume-gitlab-logs:/var/log/gitlab
       - volume-gitlab-config:/etc/gitlab
    ports:
      - "10080:10080"
      - "10022:22"
      - "10443:443"
    environment:
      http_port: 10080  # 暂时这么搞
      root_pass: password # 暂时这么搞
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.test.com:10080'
        gitlab_rails['gitlab_shell_ssh_port'] = 10022
        gitlab_rails['initial_root_password'] = "password"
        gitlab_rails['initial_shared_runners_registration_token'] = "initial_shared_runners_registration_token"
        gitlab_rails['time_zone'] = 'Asia/Shanghai'
#       Add any other gitlab.rb configuration here, each on its own line
#       https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/files/gitlab-config-template/gitlab.rb.template

volumes:
  volume-gitlab-data: {}
  volume-gitlab-logs: {}
  volume-gitlab-config: {}